version: '2'
services:
    bankaccountkata-app:
        image: bankaccountkata
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://bankaccountkata-postgresql:5432/bankAccountKata
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bankaccountkata-postgresql:
        extends:
            file: postgresql.yml
            service: bankaccountkata-postgresql
